version: '3'

services:
      web:
            build: .
            ports:
                  - "8000:8000"
            links:
                  - mysql
            volumes:
                - .:/srv/variant_db/server
                - ./static:/srv/variant_db/server/static
      redis:
            image: "redis:alpine"
            links:
                - web

