version: '3'

services:
      mysql:
            image: mysql
            environment:
                  MYSQL_DATABASE: test_db
                  MYSQL_USER: 'root'
                  MYSQL_PASSWORD: 'password'
                  MYSQL_ROOT_PASSWORD: 'password'
                  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            ports:
                  - "3307:3306"
            volumes:
                  - ./data:/docker-entrypoint-initdb.d

      web:
            build: .
            ports:
                  - "8000:8000"
            links:
                  - mysql
            volumes:
                - .:/srv/variant_db/server
                - ./static:/srv/variant_db/server/static
      redis:
            image: "redis:alpine"
            links:
                - web

